api/urls.py
from django.urls import path

from api.views import (
    FavoritesView, IngredientsViewSet, PurchasesView, SubscriptionsView
)

urlpatterns = [
    path('v1/purchases/', PurchasesView.as_view(), name='purchase'),
    path('v1/purchases/<int:pk>/', PurchasesView.as_view(), name='purchase'),
    path(
        'v1/subscriptions/',
        SubscriptionsView.as_view(),
        name='subscription'
    ),
    path(
        'v1/subscriptions/<int:pk>/',
        SubscriptionsView.as_view(),
        name='subscription'
    ),
    path('v1/favorites/', FavoritesView.as_view(), name='favorite'),
    path('v1/favorites/<int:pk>/', FavoritesView.as_view(), name='favorite'),
    path(
        'v1/ingredients/',
        IngredientsViewSet.as_view({'get': 'list'}),
        name='ingredient'
    ),
]

foodgram/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500  # noqa
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from recipes.views import about, tech

handler404 = 'recipes.views.page_not_found' # noqa
handler500 = 'recipes.views.server_error' # noqa


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('auth/', include('users.urls')),
    path('about/', about, name='about'),
    path('tech/', tech, name='tech'),
    path('', include('recipes.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path

from recipes.views import (
    CartListView, FavoriteListView, IndexListView, ProfileView,
    RecipeCreateView, RecipeDeleteView, RecipeDetailView, RecipeUpdateView,
    SubscriptionListView, shoping_list_view
)

urlpatterns = [
    path('recipes/<slug:slug>/', RecipeDetailView.as_view(), name='recipe'),
    path('edit/<slug:slug>/', RecipeUpdateView.as_view(), name='edit'),
    path(
        'subscriptions/',
        SubscriptionListView.as_view(),
        name='subscriptions'
    ),
    path('create/', RecipeCreateView.as_view(), name='create'),
    path('delete/<slug:slug>/', RecipeDeleteView.as_view(), name='delete'),
    path('purchases/', CartListView.as_view(), name='purchases'),
    path('favorites/', FavoriteListView.as_view(), name='favorites'),
    path('profiles/<str:username>/', ProfileView.as_view(), name='profile'),
    path('shoping_txt/', shoping_list_view, name='shoping_list_txt'),
    path('cart/', CartListView.as_view(), name='cart'),
    path('', IndexListView.as_view(), name='index')]

recipes/models.py
import uuid

from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse

User = get_user_model()


class Ingredient(models.Model):
    title = models.CharField(
        max_length=256,
        verbose_name='Название',
    )
    dimension = models.CharField(max_length=128, verbose_name='ед. измерения')

    class Meta:
        ordering = ('title',)
        verbose_name = 'Инргедиент'
        verbose_name_plural = 'Ингредиенты'

    def __str__(self) -> str:
        return f'{self.title} {self.dimension}'


class Tag(models.Model):
    name = models.CharField(
        max_length=200,
        verbose_name='Тег'
    )
    slug = models.SlugField(
        unique=True,
        max_length=200,
        verbose_name='Слаг',
        default=uuid.uuid1
    )
    style = models.CharField(
        max_length=200,
        verbose_name='Стиль'
    )

    class Meta:
        ordering = ('name',)
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

    def __str__(self) -> str:
        return self.name


class Recipe(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='recipes',
        verbose_name='Автор',
    )
    title = models.CharField(max_length=256, verbose_name='Название рецепта')
    image = models.ImageField(
        upload_to='recipes/images/',
        blank=False,
        verbose_name='Картинка',
        help_text='Загрузите изображение'
    )
    text = models.TextField(verbose_name='Текстовое описание',)
    ingredients = models.ManyToManyField(
        Ingredient,
        through='RecipeIngredient',
        verbose_name='Ингредиенты'
    )
    tags = models.ManyToManyField(
        Tag,
        related_name='recipes',
        verbose_name='Тег'
    )
    time = models.PositiveIntegerField(
        verbose_name='Время приготовления (мин)',
        validators=[MinValueValidator(1)]
    )
    slug = models.SlugField(unique=True, max_length=256, default=uuid.uuid1,)
    pub_date = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        verbose_name='Дата публикации',
    )

    class Meta:
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'
        ordering = ('-pub_date',)

    def __str__(self) -> str:
        return f'{self.title} от {self.author}'

    def get_absolute_url(self):
        return reverse('recipe', kwargs={'slug': self.slug})


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        verbose_name='Рецепт',
        related_name='recipe_ingredients',
    )
    ingredient = models.ForeignKey(
        Ingredient,
        on_delete=models.CASCADE,
        verbose_name='Ингредиент',
        related_name='ingredient_recipes'
    )
    amount = models.DecimalField(
        max_digits=6,
        decimal_places=1,
        validators=[MinValueValidator(1)],
        verbose_name='Количество'
    )

    class Meta:
        verbose_name = 'Ингредиент рецепта'
        verbose_name_plural = 'Ингредиенты рецепта'

    def __str__(self) -> str:
        return (f'{self.ingredient.title} {self.amount} '
                f'{self.ingredient.dimension} в {self.recipe}'
                )


class Favorite(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь',
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Рецепт',
    )

    class Meta:
        constraints = (
            models.UniqueConstraint(
                fields=('user', 'recipe'),
                name='unique_favorite'
            ),
        )
        verbose_name_plural = 'Избранные рецепты'

    def __str__(self) -> str:
        return f'Избранное {self.user}: {self.recipe}'


class Cart(models.Model):
    customer = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='customer',
        verbose_name='Покупатель',
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        verbose_name='Рецепт',
        related_name='in_cart',
    )

    class Meta:
        constraints = (
            models.UniqueConstraint(
                fields=('customer', 'recipe',),
                name='unique_сart'
            ),
        )
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'

    def __str__(self) -> str:
        return f'Корзина {self.customer}: {self.recipe}'


class Subscription(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='subscriber',
        verbose_name='Подписчик',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='author',
        verbose_name='Автор',
    )

    class Meta:
        constraints = (
            models.UniqueConstraint(
                fields=('user', 'author',),
                name='unique_follow'
            ),
        )
        ordering = ('-author',)
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

    def __str__(self) -> str:
        return f'Подписка юзера {self.user} на {self.author}'

    def clean(self):
        if self.user == self.author:
            from django.core.exceptions import ValidationError
            raise ValidationError('Нельзя подписаться на себя')

recipes/forms.py
from django.forms import ModelForm
from django.shortcuts import get_object_or_404

from .models import Ingredient, Recipe, Tag


class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        fields = ('title', 'time', 'text', 'image',)

    def clean(self):
        self._validate_unique = True
        form_ingredients, form_tags = form_ingredients_tags(self.data)
        if not form_ingredients:
            self.add_error(None, 'Добавьте ингредиенты')
        if not form_tags:
            self.add_error(None, 'Выберите тег')
        return self.cleaned_data


def form_ingredients_tags(request):
    form_ingredients = {}
    form_tags = []
    ing_part = []
    tag_keys = Tag.objects.values_list('slug', flat=True)
    all_ingredients = Ingredient.objects.values_list('title', flat=True)
    ing_keys = ['nameIngred', 'valueIngre', 'unitsIngre']
    for field in request:
        if field in tag_keys:
            form_tags.append(get_object_or_404(Tag, slug=field).id)
            continue
        if field[:10] not in ing_keys:
            continue
        ing_part.append(request[field])
        if len(ing_part) != 3:
            continue
        title = ing_part[0]
        if title not in all_ingredients:
            ing_part = []
            continue
        amount = float(ing_part[1].replace(',', '.'))
        dimension = ing_part[2]
        if title in form_ingredients:
            form_ingredients[title][1] += amount
        else:
            ing = get_object_or_404(
                Ingredient,
                title=title,
                dimension=dimension
            )
            form_ingredients[title] = [ing, amount]
        ing_part = []

    return list(form_ingredients.values()), form_tags

recipes/views.py
from http import HTTPStatus
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from foodgram.settings import PAGE_SIZE_CART, PAGE_SIZE_INDEX
from recipes.models import (
    Cart, Recipe, RecipeIngredient, Subscription, Tag, User
)
from .forms import RecipeForm, form_ingredients_tags


class RecipeListView(ListView):
    context_object_name = 'recipe_list'
    queryset = Recipe.objects.all()
    paginate_by = PAGE_SIZE_INDEX
    page_title = None

    def get_queryset(self):
        tags_check = self.request.GET.get('tags')
        if tags_check is None:
            return self.queryset
        tags_check = tags_check.split(',')
        tags_check = Tag.objects.filter(slug__in=tags_check).distinct()
        recipes = self.queryset.filter(tags__in=tags_check).distinct()
        return recipes

    def get_context_data(self, **kwargs):
        kwargs.update({'page_title': self._get_page_title()})
        tags = Tag.objects.all()
        kwargs.update({'tags_all': tags})
        context = super().get_context_data(**kwargs)
        return context

    def _get_page_title(self):
        return self.page_title


class IndexListView(RecipeListView):
    page_title = 'Рецепты'
    template_name = 'recipes/index.html'


class FavoriteListView(LoginRequiredMixin, RecipeListView):
    page_title = 'Избранное'
    template_name = 'recipes/index.html'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(following__user=self.request.user)
        return qs


class ProfileView(RecipeListView):
    context_object_name = 'profile_list'
    template_name = 'recipes/authorRecipe.html'

    def get(self, request, *args, **kwargs):
        self.user = get_object_or_404(User, username=kwargs.get('username'))
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        qs = Recipe.objects.filter(author=self.user)
        tags = self.request.GET.get('tags', None)
        if tags is None:
            return qs
        tags = tags.split(',')
        tags = Tag.objects.filter(slug__in=tags).distinct()
        qs = qs.filter(tags__in=tags).distinct()
        return qs

    def _get_page_title(self):
        return self.user.get_full_name() or self.user.username

    def get_context_data(self, **kwargs):
        kwargs.update({
            'page_title': self._get_page_title(),
            'author': self.user})
        context = super().get_context_data(**kwargs)
        return context


class RecipeDetailView(DetailView):
    queryset = Recipe.objects.all()
    template_name = 'recipes/singlePage.html'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = (
            qs
            .prefetch_related('recipe_ingredients__ingredient')
        )
        return qs


class SubscriptionListView(LoginRequiredMixin, RecipeListView):
    context_object_name = 'subscription_list'
    template_name = 'recipes/myFollow.html'
    page_title = 'Мои подписки'
    queryset = Subscription.objects.all()

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(user=self.request.user)
        return qs


class CartListView(LoginRequiredMixin, RecipeListView):
    context_object_name = 'cart_list'
    template_name = 'recipes/shopList.html'
    page_title = 'Список покупок'
    paginate_by = PAGE_SIZE_CART
    queryset = Cart.objects.all()

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(customer=self.request.user)
        return qs


def recipe_ingredient_bulk_create(form_ingredients, recipe):
    objects = []
    for ingredient in form_ingredients:
        objects.append(
            RecipeIngredient(
                recipe=recipe,
                ingredient=ingredient[0],
                amount=ingredient[1])
        )
    RecipeIngredient.objects.bulk_create(objects)


class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    page_title = 'Создание рецепта'
    form_class = RecipeForm
    template_name = 'recipes/formRecipe.html'

    def form_valid(self, form):
        form_ingredients, form_tags = form_ingredients_tags(self.request.POST)
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        form.save()
        self.object.tags.add(*form_tags)
        recipe_ingredient_bulk_create(form_ingredients, self.object)
        form.save_m2m()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        tags = Tag.objects.all()
        kwargs.update({'tags_all': tags})
        context = super().get_context_data(**kwargs)
        return context


class RecipeDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipe
    success_url = reverse_lazy('index')


class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipe
    page_title = 'Создание рецепта'
    form_class = RecipeForm
    template_name = 'recipes/formChangeRecipe.html'

    def get_context_data(self, **kwargs):
        tags = Tag.objects.all()
        kwargs.update({'tags_all': tags})
        context = super().get_context_data(**kwargs)
        return context

    def get_initial(self):
        initial = super().get_initial()
        tags = list(Tag.objects.filter(recipes=self.object))
        initial['tags'] = tags
        initial['recipe_ingredients'] = RecipeIngredient.objects.filter(
            recipe=self.object
        )
        initial['slug'] = self.object.slug
        return initial

    def form_valid(self, form):
        form_ingredients, form_tags = form_ingredients_tags(self.request.POST)
        self.object = form.save(commit=False)
        self.object.tags.set([])
        recipeingredients = RecipeIngredient.objects.filter(recipe=self.object)
        if recipeingredients:
            recipeingredients.delete()
        form.save()
        self.object.tags.add(*form_tags)
        recipe_ingredient_bulk_create(form_ingredients, self.object)
        return super().form_valid(form)


def shoping_list_view(request):
    carts = Cart.objects.filter(customer=request.user)

    recipes = Recipe.objects.filter(in_cart__in=carts)
    recipes_ingredients = RecipeIngredient.objects.filter(
        recipe__in=recipes
    )
    ingredients = (
        recipes_ingredients.values('ingredient__title').annotate(
            total_amount=Sum('amount')
        ).values_list(
            'ingredient__title',
            'total_amount',
            'ingredient__dimension')
    )
    out = []
    for item in ingredients:
        title, amount, dimension = item
        amount = str(float(amount))
        out.append(f'{title} {amount} {dimension}\n')
    out = ''.join(sorted(out))
    filename = 'my_shoping_list.txt'
    response = HttpResponse(out, content_type='text/plain')
    response['Content-Disposition'] = f'attachment; filename={filename}'
    return response


def page_not_found(request, exception):
    return render(
        request,
        'misc/404.html',
        {'path': request.path},
        status=HTTPStatus.NOT_FOUND
    )


def server_error(request):
    return render(
        request,
        'misc/500.html',
        status=HTTPStatus.INTERNAL_SERVER_ERROR
    )


def about(request):
    return render(request, 'misc/about.html', status=HTTPStatus.OK)


def tech(request):
    return render(request, 'misc/tech.html', status=HTTPStatus.OK)

templates/recipes/authorRecipe.html
{% extends 'base.html' %}
{% load static %}
{% load recipe_extras %}

{% block page_title %}
    {{ page_title }}
{% endblock %}

{% block static_css %}
    <link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}

{% block content %}
    <div class="main__header">
        <h1 class="main__title">{{ page_title }}</h1>
        {% include 'includes/filter_tags.html' %}
    </div>
    {% if user.is_authenticated %}
        {% if user.username not in request.path %}
            <div class="author-subscribe" data-author="{{ author.id }}">
                {% if author|in_subs:user %}
                    <p style="padding: 0 0 2em 0;"><button class="button button_style_light-blue" name="subscribe">Отписаться от автора</button></p>    
                {% else %}
                    <p style="padding: 0 0 2em 0;"><button class="button button_style_light-blue button_size_subscribe" name="subscribe" data-out>Подписаться на автора</button></p>
                {% endif %}
            </div>
        {% endif %}
    {% endif %}
    </div>
    <div class="card-list">
        {% for recipe in page_obj %}
            {% include 'includes/recipe_card.html' with recipe=recipe %}
        {% endfor %}
    </div>

    {% if page_obj.has_other_pages %}
        {% include 'includes/paginator.html'  with items=page_obj paginator=paginator %}
    {% endif %}
{% endblock %}

{% block static_js %}
        <script src="{% static 'js/components/MainCards.js' %}"></script>
        <script src="{% static 'js/components/Purchases.js' %}"></script>
    {% if user.is_authenticated %}
        <script src="{% static 'js/components/Favorites.js' %}"></script>
    {% endif %}
        <script src="{% static 'js/components/Subscribe.js' %}"></script>
        <script src="{% static 'js/config/config.js' %}"></script>
        <script src="{% static 'js/components/AuthorRecipe.js' %}"></script>
        <script src="{% static 'js/components/Header.js' %}"></script>
        <script src="{% static 'js/api/Api.js' %}"></script>
        <script src="{% static 'js/templates/recipes/authorRecipe.js' %}"></script>
{% endblock %}

templates/recipes/formChangeRecipe.html
{% extends 'base.html' %}
{% load static %}
{% load recipe_extras %}

{% block page_title %}
    Редактирование рецепта
{% endblock %}

{% block static_css %}
    <link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}

{% block content %}
    <div class="main__header">
        <h1 class="main__title">Редактирование рецепта</h1>
    </div>
    <div class="form-container">
        <form class="form" method="post" action="{% url 'edit' slug=form.initial.slug %}" enctype="multipart/form-data" autocomplete="off">
            {% csrf_token %}
            <div class="form__group">
                <label for="id_name" class="form__label">Название рецепта</label>
                <div class="form__field-group">
                    {{ form.title|addclass:"form__input"}}
                    <span class="form__error">{{ form.title.errors }}</span>
                </div>
            </div>
            <div class="form__group">
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    {% include 'includes/form_tags.html' %}
                </div>
                <span class="form__error">
                    {% for error in form.non_field_errors %}
                        {% if 'тег' in error %}{{ error }}{% endif %}
                    {% endfor %}
                </span>
            </div>

            <div class="form__group">
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="0">
                        <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                    </div>
                    <div class="form__field-group-ingredientes-container">
                        {% for ing in form.initial.recipe_ingredients %}
                            <div class="form__field-item-ingredient" id="{{ ing.pk }}">
                                <span>{{ ing.ingredient.title }} {{ ing.amount }} {{ ing.ingredient.dimension }}</span>
                                <span class="form__field-item-delete" ></span>
                                <input id="nameIngredient_{{ ing.pk }}" name="nameIngredient_{{ ing }}" type="hidden" value="{{ ing.ingredient.title }}">
                                <input id="valueIngredient_{{ ing.pk }}" name="valueIngredient_{{ ing }}" type="hidden" value="{{ ing.amount }}">
                                <input id="unitsIngredient_{{ ing.pk }}" name="unitsIngredient_{{ ing }}" type="hidden" value="{{ ing.ingredient.dimension }}">
                            </div>
                        {% endfor %}
                    </div>
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    <span class="form__error">
                        {% for error in form.non_field_errors %}
                            {% if 'ингредиенты' in error %}{{ error }}{% endif %}
                        {% endfor %}
                    </span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_time" class="form__label">Время приготовления</label>
                <div class="form__field-group form__field-group_time">
                    {{ form.time|addclass:"form__input"}}
                    <label for="id_time" class="form__label">минут</label>
                    <span class="form__error">{{ form.time.errors }}</span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_description" class="form__label">Описание</label>
                <div class="form__field-group">
                    {{ form.text|addclass:"form__textarea"}}
                    <span class="form__error">{{ form.text.errors }}</span>
                </div>
            </div>
            <div class="form__group">
                <span class="form__label">Загрузить фото</span>
                <div class="form__field-group">
                    <label for="id_file" class="form__file-button">Выбрать файл</label>
                    <input type="file" class="form__file" name="image" id="id_file">
                    <span class="form__error">{{ form.image.errors }}</span>
                </div>
            </div>
            <div class="form__footer">
                <button class="button button_style_blue">Сохранить</button> <a style="margin-left: 2.5em" href="{% url 'delete' slug=object.slug %}" class="form__ingredient-link">Удалить</a>
            </div>
        </form>
    </div>
{% endblock %}



{% block static_js %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/utils/debouncing.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/templates/recipes/formRecipe.js' %}"></script>
{% endblock %}

templates/recipes/formRecipe.html
{% extends 'base.html' %}
{% load static %}
{% load recipe_extras %}

{% block page_title %}
    Создание рецепта
{% endblock %}

{% block static_css %}
    <link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}

{% block content %}

<div class="main__header">
    <h1 class="main__title">Создание рецепта</h1>
</div>
<div class="form-container">
    <form class="form" method="post" action="{% url 'create' %}" enctype="multipart/form-data" autocomplete="off">
        {% csrf_token %}
        <div class="form__group">
            <label for="id_name" class="form__label">Название рецепта</label>
            <div class="form__field-group">
                <input type="text" id="id_name" name="title" class="form__input" value="{% if form.title.value %}{{ form.title.value }}{% endif %}">
                <span class="form__error">{{ form.title.errors }}</span>
            </div>
        </div>
        <div class="form__group">
            <p class="form__label">Теги</p>
            <div class="form__field-group">
                {% include 'includes/form_tags.html' %}
                <span class="form__error">
                    {% for error in form.non_field_errors %}
                        {% if 'тег' in error %}{{ error }}{% endif %}
                    {% endfor %}
                </span>
            </div>
        </div>
        <div class="form__group">
            <label for="nameIngredient" class="form__label">Ингредиенты</label>
            <div class="form__field-group">
                <div class="form__field-group-ingredientes">
                    <div class="form__dropdown">
                        <input type="text" id="nameIngredient" class="form__input">
                        <div class="form__dropdown-items"></div>
                    </div>
                    <input type="number" id="cantidad" class="form__input" min="0">
                    <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                </div>
                <div class="form__field-group-ingredientes-container">
                    {% for ing in form.instance.IngredientRecipe_set.all %}
                        <div class="form__field-item-ingredient" id="{{ ing.pk }}">
                            <span>{{ ing.ingredient.title }} {{ ing.ingredient.amount }} {{ ing.ingredient.dimension }}</span>
                            <span class="form__field-item-delete" ></span>
                            <input id="nameIngredient_{{ ing.pk }}" name="nameIngredient_{{ ing }}" type="hidden" value="{{ ing.ingredient.title }}">
                            <input id="valueIngredient_{{ ing.pk }}" name="valueIngredient_{{ ing }}" type="hidden" value="{{ ing.amount }}">
                            <input id="unitsIngredient_{{ ing.pk }}" name="unitsIngredient_{{ ing }}" type="hidden" value="{{ ing.ingredient.dimension }}">
                        </div>
                    {% endfor %}
                </div>
                <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>

                <span class="form__error">
                    {% for error in form.non_field_errors %}
                        {% if 'ингредиенты' in error %}{{ error }}{% endif %}
                    {% endfor %}
                </span>
            </div>
        </div>
        <div class="form__group">
            <label for="id_time" class="form__label">Время приготовления</label>
            <div class="form__field-group form__field-group_time">
                <input type="text" id="id_time" name="time" class="form__input" value="{% if form.time.value %}{{ form.time.value }}{% endif %}">
                <label for="id_time" class="form__label">минут</label>
                <span class="form__error">{{ form.time.errors }}</span>
            </div>
        </div>
        <div class="form__group">
            <label for="id_description" class="form__label">Описание</label>
            <div class="form__field-group">
                <textarea name="text" id="id_description" rows="8" class="form__textarea" value="{% if form.text.value %}{{ form.text.value }}{% endif %}"></textarea>
                <span class="form__error">{{ form.text.errors }}</span>
            </div>
        </div>
        <div class="form__group">
            <span class="form__label">Загрузить фото</span>
            <div class="form__field-group">
                <label for="id_file" class="form__file-button">Выбрать файл</label>
                <input type="file" class="form__file" name="image" id="id_file" value="{% if form.image.value %}{{ form.image.value }}{% endif %}">
                <span class="form__error">{{ form.image.errors }}</span>
            </div>
        </div>

        <div class="form__footer">
            <button class="button button_style_blue">Создать рецепт</button>
        </div>
    </form>
</div>
{% endblock %}

{% block static_js %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/utils/debouncing.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/templates/recipes/formRecipe.js' %}"></script>
{% endblock %}

templates/recipes/recipe_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}
    {{ page_title }}
{% endblock %}

{% block static_css %}
    <link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <center><h1>Подтвердите удаление</h1></center>
        <div class="custom-center-block">
            <p class="custom-text-block">Вы уверены, что хотите удалить "{{ object }}"?</p>
        </div>
        <div class="custom-button-block">
            <input class="button button_style_blue" type="submit" value="Подтвердить">
        </div>
    </form>
{% endblock %}